In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\py19\Data-Collisions (2).csv")
df

C:\Users\taran\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194668,2,-122.290826,47.565408,219543,309534,310814,E871089,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,24,From opposite direction - both moving - head-on,0,0,N
194669,1,-122.344526,47.690924,219544,309085,310365,E876731,Matched,Block,NaN,...,Wet,Daylight,NaN,NaN,NaN,13,From same direction - both going straight - bo...,0,0,N
194670,2,-122.306689,47.683047,219545,311280,312640,3809984,Matched,Intersection,24760.0,...,Dry,Daylight,NaN,NaN,NaN,28,From opposite direction - one left turn - one ...,0,0,N
194671,2,-122.355317,47.678734,219546,309514,310794,3810083,Matched,Intersection,24349.0,...,Dry,Dusk,NaN,NaN,NaN,5,Vehicle Strikes Pedalcyclist,4308,0,N
194672,1,-122.289360,47.611017,219547,308220,309500,E868008,Matched,Block,NaN,...,Wet,Daylight,NaN,NaN,NaN,14,From same direction - both going straight - on...,0,0,N

In [3]:
df.shape

(194673, 38)

In [4]:
data=df[['WEATHER','ROADCOND','LIGHTCOND','SEVERITYCODE']]
data

         WEATHER ROADCOND                LIGHTCOND  SEVERITYCODE
0       Overcast      Wet                 Daylight             2
1        Raining      Wet  Dark - Street Lights On             1
2       Overcast      Dry                 Daylight             1
3          Clear      Dry                 Daylight             1
4        Raining      Wet                 Daylight             2
...          ...      ...                      ...           ...
194668     Clear      Dry                 Daylight             2
194669   Raining      Wet                 Daylight             1
194670     Clear      Dry                 Daylight             2
194671     Clear      Dry                     Dusk             2
194672     Clear      Wet                 Daylight             1

[194673 rows x 4 columns]

In [5]:
inputs = data.drop('SEVERITYCODE',axis='columns')

In [6]:
target = data['SEVERITYCODE']

In [7]:
target

0         2
1         1
2         1
3         1
4         2
         ..
194668    2
194669    1
194670    2
194671    2
194672    1
Name: SEVERITYCODE, Length: 194673, dtype: int64

In [8]:
inputs

         WEATHER ROADCOND                LIGHTCOND
0       Overcast      Wet                 Daylight
1        Raining      Wet  Dark - Street Lights On
2       Overcast      Dry                 Daylight
3          Clear      Dry                 Daylight
4        Raining      Wet                 Daylight
...          ...      ...                      ...
194668     Clear      Dry                 Daylight
194669   Raining      Wet                 Daylight
194670     Clear      Dry                 Daylight
194671     Clear      Dry                     Dusk
194672     Clear      Wet                 Daylight

[194673 rows x 3 columns]

In [9]:
df1=inputs.dropna()
df1.shape

(189337, 3)

In [10]:
df1

         WEATHER ROADCOND                LIGHTCOND
0       Overcast      Wet                 Daylight
1        Raining      Wet  Dark - Street Lights On
2       Overcast      Dry                 Daylight
3          Clear      Dry                 Daylight
4        Raining      Wet                 Daylight
...          ...      ...                      ...
194668     Clear      Dry                 Daylight
194669   Raining      Wet                 Daylight
194670     Clear      Dry                 Daylight
194671     Clear      Dry                     Dusk
194672     Clear      Wet                 Daylight

[189337 rows x 3 columns]

In [11]:
Feature=df['SEVERITYDESC']
Feature=pd.concat([Feature, pd.get_dummies(df[['WEATHER','ROADCOND','LIGHTCOND']])], axis=1)

Feature.head()

,SEVERITYDESC,WEATHER_Blowing Sand/Dirt,WEATHER_Clear,WEATHER_Fog/Smog/Smoke,WEATHER_Other,WEATHER_Overcast,WEATHER_Partly Cloudy,WEATHER_Raining,WEATHER_Severe Crosswind,WEATHER_Sleet/Hail/Freezing Rain,...,ROADCOND_Wet,LIGHTCOND_Dark - No Street Lights,LIGHTCOND_Dark - Street Lights Off,LIGHTCOND_Dark - Street Lights On,LIGHTCOND_Dark - Unknown Lighting,LIGHTCOND_Dawn,LIGHTCOND_Daylight,LIGHTCOND_Dusk,LIGHTCOND_Other,LIGHTCOND_Unknown
0,Injury Collision,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,Property Damage Only Collision,0,0,0,0,0,0,1,0,0,...,1,0,0,1,0,0,0,0,0,0
2,Property Damage Only Collision,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,Property Damage Only Collision,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,Injury Collision,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,1,0,0,0

In [12]:
Feature.drop(['SEVERITYDESC'], axis=1, inplace=True)
Feature

,WEATHER_Blowing Sand/Dirt,WEATHER_Clear,WEATHER_Fog/Smog/Smoke,WEATHER_Other,WEATHER_Overcast,WEATHER_Partly Cloudy,WEATHER_Raining,WEATHER_Severe Crosswind,WEATHER_Sleet/Hail/Freezing Rain,WEATHER_Snowing,...,ROADCOND_Wet,LIGHTCOND_Dark - No Street Lights,LIGHTCOND_Dark - Street Lights Off,LIGHTCOND_Dark - Street Lights On,LIGHTCOND_Dark - Unknown Lighting,LIGHTCOND_Dawn,LIGHTCOND_Daylight,LIGHTCOND_Dusk,LIGHTCOND_Other,LIGHTCOND_Unknown
0,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194668,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
194669,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
194670,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
194671,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
194672,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0

In [13]:
X=Feature
X[0:5]

,WEATHER_Blowing Sand/Dirt,WEATHER_Clear,WEATHER_Fog/Smog/Smoke,WEATHER_Other,WEATHER_Overcast,WEATHER_Partly Cloudy,WEATHER_Raining,WEATHER_Severe Crosswind,WEATHER_Sleet/Hail/Freezing Rain,WEATHER_Snowing,...,ROADCOND_Wet,LIGHTCOND_Dark - No Street Lights,LIGHTCOND_Dark - Street Lights Off,LIGHTCOND_Dark - Street Lights On,LIGHTCOND_Dark - Unknown Lighting,LIGHTCOND_Dawn,LIGHTCOND_Daylight,LIGHTCOND_Dusk,LIGHTCOND_Other,LIGHTCOND_Unknown
0,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0

In [14]:
y=target
y

0         2
1         1
2         1
3         1
4         2
         ..
194668    2
194669    1
194670    2
194671    2
194672    1
Name: SEVERITYCODE, Length: 194673, dtype: int64

# Model Development and Evaluation

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print('train set:', X_train.shape, y_train.shape)
print('test set:', X_test.shape, y_test.shape)

train set: (136271, 29) (136271,)
test set: (58402, 29) (58402,)

# Methodology
Our data is now ready to be fed into machine learning models.

We will use the following models:

# K-Nearest Neighbor (KNN)
KNN will help us predict the severity code of an outcome by finding the most similar to data point within k distance.

## K-Nearest Neighbors (KNN)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
k=25

In [31]:
neigh=KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
neigh
kyhat=neigh.predict(X_test)
kyhat

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [18]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
jaccard_similarity_score(y_test,kyhat)

C:\Users\taran\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

0.6938230383973288

In [19]:
f1_score(y_test,kyhat,average='macro')

0.4315007296192111

## Decision Tree Model

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing

In [21]:
from sklearn.tree import DecisionTreeClassifier
colDataTree = DecisionTreeClassifier(criterion="entropy",max_depth =7)
colDataTree
colDataTree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [33]:
Dyhat = colDataTree.predict(X_test)
print(Dyhat[0:5])
print(y_test[0:5])

[1 1 1 1 1]
181980    2
163332    1
180525    1
1695      2
143631    2
Name: SEVERITYCODE, dtype: int64

In [34]:
jaccard_similarity_score(y_test,Dyhat)

C:\Users\taran\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

0.7034519365775145

In [35]:
f1_score(y_test,kyhat,average='macro')

0.4129567271447957

# Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=6, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
LRyhat =LR.predict(X_test)
LRyhat[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [37]:
yhat_prob =LR.predict_proba(X_test)
yhat_prob

array([[0.63996822, 0.36003178],
       [0.66128596, 0.33871404],
       [0.69705016, 0.30294984],
       ...,
       [0.66306871, 0.33693129],
       [0.73622233, 0.26377767],
       [0.66306871, 0.33693129]])

In [38]:
jaccard_similarity_score(y_test,LRyhat)

C:\Users\taran\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

0.7034348138762371

In [39]:
f1_score(y_test,kyhat,average='macro')

0.4129567271447957

# Evaluation
#### K-Nearest Neighbors (KNN)

In [26]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score

In [27]:
jaccard_similarity_score(y_test,kyhat)

C:\Users\taran\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

0.6938230383973288

In [28]:
f1_score(y_test,kyhat,average='macro')

0.4315007296192111